apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-project-deployment
  labels:
    app: toprefunder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toprefunder
  template:
    metadata:
      labels:
        app: toprefunder
    spec:
      containers:
      - name: react-project
        image: tomcoder/reactimages:latest
        ports:
        - name: image-port
          containerPort: 5173
